import { Box, Button, Image, Text, useColorMode } from "@chakra-ui/react";
import { NextPage } from "next";
import Head from "next/head";
import LandingIntro from "../components/landingIntro";

const Home: NextPage = () => {
  return (
    <Box backgroundColor="background" h="100%">
      <Head>
        <title>wtf-ai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LandingIntro />
    </Box>
  );
};

export default Home;
